apiVersion: v1
kind: Service
metadata:
    name: "fabmedicaleaq-a463"
    labels:
        app: "fabmedicaleaq-a463"
spec:
    type: LoadBalancer
    ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    selector:
        app: "fabmedicaleaq-a463"