on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fabmedicaleaq.azurecr.io
        username: ${{ secrets.acr_fabmedicaleaq_username }}
        password: ${{ secrets.acr_fabmedicaleaq_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/content-api" -f  "content-api/Dockerfile" -t fabmedicaleaq.azurecr.io/fabmedicaleaq:${{ github.sha }} --label dockerfile-path=content-api/Dockerfile
        docker push fabmedicaleaq.azurecr.io/fabmedicaleaq:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fabmedicaleaq_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fabmedical-eaq9f9f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fabmedical-eaq9f9f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fabmedical-eaq9f9f
        container-registry-url: fabmedicaleaq.azurecr.io
        container-registry-username: ${{ secrets.acr_fabmedicaleaq_username }}
        container-registry-password: ${{ secrets.acr_fabmedicaleaq_password }}
        secret-name: fabmedicaleadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fabmedical-eaq9f9f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          fabmedicaleaq.azurecr.io/fabmedicaleaq:${{ github.sha }}
        imagepullsecrets: |
          fabmedicaleadockerauth
